application: study-electric
version: 1
runtime: go
api_version: go1

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /index\.html
  static_files: index.html
  upload: index.html

- url: /electronics
  static_dir: electronics

- url: /timer
  static_dir: timer

- url: /.*
  script: _go_app
  secure: always
